<?php

########################################################################
# Extension Manager/Repository config file for ext: "twitter_feed"
#
# Auto generated by Extbase Kickstarter 2010-05-30
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Twitter Feed',
	'description' => 'Fetches and displays a twitter feed for defined accounts',
	'category' => 'plugin',
	'author' => 'Remco Overdijk',
	'author_email' => 'remco@maxserv.nl',
	'author_company' => 'MaxServ B.V.',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>